
name: Publish by Tag

on:
  push:
    tags: ["*"]


jobs:

  publish:

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, arm64]

    runs-on: windows-latest

    env:
      Solution_Name: Pica3.sln
      Configuration: ${{ matrix.configuration }}
      Platform: ${{ matrix.platform }}
      Publish_Path: ./Pica3/bin/${{ matrix.platform }}/${{ matrix.configuration }}/bika3
      Tag_Name: ${{ github.ref_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore the packages
      run: dotnet restore

    - name: Publish the Application
      run: |
        $tag = ${{env.Tag_Name}}
        if ($tag.StartsWith('v') -or $tag.StartsWith('V')) {
            $tag = $tag.SubString(1)
        }
        dotnet publish ./Pica3/Pica3.csproj -p:Configuration=$env:Configuration -p:Platform=$env:Platform -p:Version=$tag
        $time = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss zzz')
        Add-Content -Path $env:Publish_Path/!看这里.txt -Value "`n`n${{env.Tag_Name}}`nBuild by GitHub Actions automatically.`n$time`n"
        New-Item -Path ./publish -ItemType Directory -Force

    - name: Delete Useless Folder
      run: Get-ChildItem -Path $env:Publish_Path -Directory | Where { $_.Name -ne "en-us" -and $_.Name -ne "Microsoft.UI.Xaml" } | Remove-Item -Recurse

    - name: Compress Published Files
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Install-Module -Name 7Zip4Powershell -Scope CurrentUser -Force
        New-Item -Path ./publish -ItemType Directory -Force
        Compress-7Zip -ArchiveFileName bika3_${{env.Tag_Name}}_${{env.Platform}}.7z -Path $env:Publish_Path -OutputPath ./publish -CompressionLevel Ultra -PreserveDirectoryRoot

    - name: Create Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        draft: true
        files: ./publish/*